@user-url=http://localhost:8000/api/users
@artist-url=http://localhost:8000/api/artists
@show-url=http://localhost:8000/api/shows
@freindReq-url=http://localhost:8000/api/friendReqs

### GET users
GET {{user-url}}
### GET user by username
GET {{user-url}}/pipo
### POST user
POST {{user-url}}
Content-Type: application/json

{
    "name": "hallo2",
    "password": "geheim123"
}
### Delete user
DELETE {{user-url}}/hallo2